export interface CampaignInfo {
  id: number,
  type: "campaign",
  attributes: CampaignInfoAttributes
}

export interface CampaignInfoAttributes {
  id: number,
  name: string,
  stream: number,
  disabled: boolean,
  type_id: number,
  isp: string,
  weekdays: unknown[],
  hours: unknown[],
  use_whitelist_domains: boolean,
  blacklist_domains: unknown[],
  whitelist_domains: unknown[],
  size_id: number,
  ip_range_type: number,
  use_whitelist_user_agents: boolean,
  blacklist_user_agents: unknown[],
  whitelist_user_agents: unknown[],
  keywords: string[],
  spots_list_ids: unknown[],
  ip_list_ids: unknown[],
  spot_ids: string[],
  connection_type_ids: unknown[],
  device_ids: unknown[],
  browser_ids: unknown[],
  specific_platforms: unknown[],
  platform_ids: unknown[],
  specific_browsers: unknown[],
  language_ids: unknown[],
  city_ids: unknown[],
  region_ids: unknown[],
  ron_type: number,
  country_codes: unknown[],
  start_at: string,
  finish_at: string,
  limits: unknown[],
  cpm_floor_to_confirm: string,
  ips: string[],
  use_whitelist_ip: boolean
}
